A	backend/src/controllers/cartController.js
A	backend/src/controllers/customerController.js
A	backend/src/controllers/employeeController.js
A	backend/src/controllers/orderController.js
A	backend/src/controllers/paymentController.js
A	backend/src/controllers/salaryController.js
M	backend/src/controllers/userController.js
A	backend/src/models/cartModel.js
A	backend/src/models/customerModel.js
A	backend/src/models/customerPaymentModel.js
A	backend/src/models/employeeModel.js
A	backend/src/models/orderModel.js
A	backend/src/models/salaryModel.js
A	backend/src/routes/customerRoutes.js
A	backend/src/routes/employeeRoutes.js
A	backend/src/routes/orderRoutes.js
A	backend/src/routes/paymentRoutes.js
A	backend/src/routes/salaryRoutes.js
M	backend/src/routes/userRoutes.js
M	backend/src/server.js
M	frontend/package-lock.json
M	frontend/package.json
M	frontend/src/App.jsx
A	frontend/src/components/Carousel.jsx
A	frontend/src/components/Cart.jsx
A	frontend/src/components/CheckoutCustomerDetails.jsx
A	frontend/src/components/CheckoutPayment.jsx
A	frontend/src/components/CustomerLogin.jsx
A	frontend/src/components/CustomerRegister.jsx
A	frontend/src/components/Dashboard/DashboardLayout.jsx
A	frontend/src/components/Dashboard/PieChart.jsx
A	frontend/src/components/Dashboard/StatCards.jsx
A	frontend/src/components/Footer.jsx
A	frontend/src/components/GoogleMapSelector.jsx
A	frontend/src/components/Header.jsx
A	frontend/src/components/Homepage.jsx
A	frontend/src/components/OrderConfirmation.jsx
A	frontend/src/components/ProductDetails.jsx
A	frontend/src/components/ProductListing.jsx
A	frontend/src/components/StaffLogin.jsx
A	frontend/src/components/admin/AdminDashboard.jsx
A	frontend/src/components/admin/CustomerManagement.jsx
A	frontend/src/components/admin/EmployeeManagement.jsx
A	frontend/src/components/admin/FarmerManagement.jsx
A	frontend/src/components/admin/UserManagement.jsx
A	frontend/src/components/finance/CalculateSalary.jsx
A	frontend/src/components/finance/FinanceDashboard.jsx
A	frontend/src/data/adminData.js
A	frontend/src/data/financeData.js
A	frontend/src/test-maps.html
M	frontend/vite.config.js
A	package.json
